#!/bin/bash

docker build -t cresson-api .
[ $? -eq 0 ] || exit $?

docker container stop cresson-api
docker container rm cresson-api
docker run --detach --restart always \
    --name=cresson-api \
    --network=cresson-network \
    -p 2400:80 \
    -e CRESSON_API_PORT=80 \
    -e CRESSON_API_AUTH_SECRET \
    -e CRESSON_API_DB_DRIVER \
    -e CRESSON_API_DB_CONNECT \
    -e CRESSON_API_DEBUG \
    cresson-api
