#!/bin/bash

docker build -t cresson-api .
[ $? -eq 0 ] || exit $?

docker stop cresson-api
docker run --rm --detach \
    --name=cresson-api \
    --network=cresson-network \
    -p 2400:80 \
    -e CRESSON_PORT=80 \
    -e CRESSON_AUTH_SECRET \
    -e CRESSON_DB_DRIVER \
    -e CRESSON_DB_CONNECT \
    -e CRESSON_DEBUG \
    cresson-api
