#!/bin/bash

docker build -t cresson-php .

docker container stop cresson-php
docker container rm cresson-php
docker run --detach --restart always \
    -p 9000:9000 \
    --name=cresson-php \
    --network=cresson-network \
    -e CRESSON_MYSQL_HOST \
    -e CRESSON_MYSQL_PORT \
    -e CRESSON_MYSQL_ROOT_PASSWORD \
    -v /var/lib/cresson/html:/var/lib/cresson/html \
    cresson-php
