#!/bin/bash

# ref: https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

# get config from home directory if exists
'cp' cresson.conf cresson.conf.save
'cp' ~/cresson.conf .

go get github.com/pkg/errors github.com/gin-gonic/gin github.com/dgrijalva/jwt-go github.com/go-sql-driver/mysql
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o bin/cresson .
[ $? -eq 0 ] || exit $?
docker build -t cresson .

# restore config file
mv -f cresson.conf.save cresson.conf
