#!/bin/bash

CURRENT=$(docker ps -a -q --filter ancestor=cresson)

docker build -t cresson .
[ $? -eq 0 ] || exit $?

[ -z "$CURRENT" ] || docker stop $CURRENT
docker run --rm --detach \
    -p 2424:80 \
    -e CRESSON_PORT=80 \
    -e CRESSON_AUTH_SECRET \
    -e CRESSON_DB_DRIVER \
    -e CRESSON_DB_CONNECT \
    -e CRESSON_DEBUG \
    -v /var/lib/mysql/mysql.sock:/mysql.sock \
    cresson
