#!/bin/bash

CURRENT=$(docker ps -a -q --filter ancestor=cresson)

# get config from home directory if exists
'cp' cresson.conf cresson.conf.save
'cp' ~/cresson.conf .

docker build -t cresson .
result=$?

# restore config file
mv -f cresson.conf.save cresson.conf

[ $result -eq 0 ] || exit $?

docker stop $CURRENT
docker run --rm --network="host" --detach cresson
