version: '2'

services:
  api:
    build: ./api
    image: cresson-api
    container_name: cresson-api
    hostname: cresson-api
    networks:
      - cresson-network
    ports:
      - "2400:80/tcp"
    environment:
      - CRESSON_API_PORT=80
      - CRESSON_API_AUTH_SECRET
      - CRESSON_API_DB_DRIVER
      - CRESSON_API_DB_CONNECT
      - CRESSON_API_DEBUG
    restart: always
    mem_limit: 500M

  db:
    image: mysql:5.7
    container_name: cresson-db
    hostname: cresson-db
    networks:
      - cresson-network
    environment:
      - MYSQL_ROOT_PASSWORD=${CRESSON_MYSQL_ROOT_PASSWORD}
    volumes:
      - cresson-db-vol:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    mem_limit: 1G

volumes:
  cresson-db-vol:
    external: true

networks:
  cresson-network:
    external: true
