#!/bin/bash

docker container stop cresson-db
docker container rm cresson-db
mkdir -p /var/lib/cresson/mysql
docker run --detach --restart always \
    --name=cresson-db \
    --network=cresson-network \
    --env MYSQL_ROOT_PASSWORD=$CRESSON_MYSQL_ROOT_PASSWORD \
    --mount type=volume,source=cresson-db-vol,target=/var/lib/mysql \
    --mount type=bind,source=$(pwd)/db.sql,target=/docker-entrypoint-initdb.d/db.sql \
    --memory=1G \
    mysql:5.7

