#!/bin/bash

docker stop cresson-db
mkdir -p /var/lib/cresson/mysql
docker run --rm --detach \
    --name=cresson-db \
    --network=cresson-network \
    -e MYSQL_ROOT_PASSWORD=$CRESSON_MYSQL_ROOT_PASSWORD \
    -v /var/lib/cresson/mysql:/var/lib/mysql \
    -v $(pwd)/db.sql:/docker-entrypoint-initdb.d/db.sql \
    mysql:5.6
